services:
  postgres:
    image: postgres:17
    container_name: postgres_my_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-devuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_DB: ${DB_NAME:-devdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    container_name: redis_my_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:latest
    container_name: kafka_my_broker
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # 1. MAP: Объясняем Кафке, что INTERNAL и EXTERNAL - это обычные протоколы без SSL (PLAINTEXT)
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # 2. ДВЕРИ: Открываем три порта: 29092 (внутренний), 9092 (внешний) и 9093 (контроллер)
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      # 3. ВИЗИТКИ: Соседям по Докеру даем адрес kafka:29092, а твоей Java-программе — localhost:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      # 4. Указываем, какую дверь Кафка использует для общения внутри кластера
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=MyLocalKafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
  chat-backend:
    build: ./chat-server # Ищет Dockerfile в папке chat-server
    container_name: spring_boot_server
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # ВАЖНО: Внутри докера "localhost" не работает! Мы заменяем его на имена контейнеров.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatdb
      - SPRING_DATA_REDIS_HOST=redis
      # Сервер внутри Докера стучится во внутреннюю "дверь" Кафки (29092)
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - postgres
      - redis
      - kafka
volumes:
  pgdata:
